#!/usr/bin/env bash
#Install ngnix in the web server
sudo apt update
sudo apt -y install nginx
sudo service nginx start
sudo echo "Holberton School" | sudo tee /var/www/html/index.html
sudo service nginx restart
