#!/usr/bin/env bash
#Install ngnix in the web server
sudo apt-get install update
sudo apt-get upgrade
sudo apt-get -y install nginx
sudo echo "Holberton School" > /var/www/html/index.html
sudo service nginx start
