#!/usr/bin/env bash
#Script for redirection 301
sudo apt-get update
sudo apt-get -y install nginx
echo "Holberton School" | sudo tee /var/www/html/index.html
sudo service nginx restart
str = "/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4;"
sudo sed -i "37i $str" /etc/nginx/sites-available/default
sudo service nginx restart
