#!/usr/bin/env bash
#Script for configure my Mginx server to have custon 404 page
sudo apt-get -y update
sudo apt-get -y install nginx
rule="add_header X-Served-By $(hostname);"
sudo sed -i "46 i ${rule}" /etc/nginx/sites-enabled/default 
sudo service nginx restart
