#!/usr/bin/env bash
#Script for configure my Mginx server to have custon 404 page
sudo apt-get -y update
sudo apt-get -y install nginx
VALUE="add_header X-Served-By $(HOSTNAME);"
sudo sed -i "50i ${VALUE}" /etc/nginx/sites-enabled/default 
sudo service nginx restart
