#!/usr/bin/env bash
#Script for install a load balancer
sudo apt-get install software-properties-common -y
sudo add-apt-repository ppa:vbernat/haproxy-2.0 -y
sudo apt-get update -y
sudo apt-get install haproxy=2.0.\* -y
front="frontend 945-lb-01
bind *:80
mode http
default_backend My_Web_Servers"
back="backend My_Web_Servers
mode http
balance roundrobin
option forwardfor
option httpchk HEAD / HTTP/1.1rnHost:localhost
server 945-web-01 35.237.170.159:80 check
server 945-web-02 35.231.101.25:80 check"
echo -e "$front\n$back" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart
