#!/usr/bin/env bash
#Make loop with 10 iteration but print "bad luck" in the
#4to iteration and print "good luck" in the 8th iteration
#in the other interation print "Holberton School"
COUNT=0
while [ $COUNT -lt 10 ];do
    if [ $COUNT -eq 3 ];then
	echo "Bad Luck"
    elif [ $COUNT -eq 7 ];then
	echo "Good luck"
    else
	echo "Holberton School"
    fi
    let COUNT=COUNT+1
done
