#!/usr/bin/env bash
#Make loop with 10 iteration but print "bad luck" in the
#4to iteration and print "good luck" in the 8th iteration
#in the other interation print "Holberton School"
COUNT=1
while [ $COUNT -le 10 ];do
    if [ $COUNT -eq 4 ];then
	echo "bad Luck"
    elif [ $COUNT -eq 8 ];then
	echo "good luck"
    else
	echo "Holberton School"
    fi
    let COUNT=COUNT+1
done
