#!/usr/bin/env bash
#Print "bad luck from China" in the 4to iterator
#Print "bad luck from Japan" in the 9ne iterator
#Print "bad luck from Italy" in the 17tn iterator
#if you don't print the value
I=1
while [ $I -le 20 ];do
    echo $I
    case $I in 4)
	    echo "bad luck from China"
	    ;;
    9)
	    echo "bad luck from Japan"
	    ;;
    17)
	    echo "bad luck from Italy"
	    ;;
    esac
    let I=I+1
done
