#!/usr/bin/env bash
#Script of bash to kill apache 2, start nginx on port 8080 and run
sudo pkill -u root apache2
sudo chown nginx:nginx /etc/nginx/nginx.conf
sudo chmod  700 /etc/nginx/nginx.conf
sudo sed -i 's!80 !8080 !' /etc/nginx/sites-available/default
sudo -u nginx service nginx restart
